"""Render described queries as a Python module.

Output shape, one module per input .sql file:

    @dataclass(frozen=True, slots=True)
    class GetOrderWithUserRow:
        id: UUID
        email: str | None

    def get_order_with_user(
        conn: psycopg.Connection[tuple[object, ...]], *, order_id: UUID
    ) -> GetOrderWithUserRow | None: ...

The connection parameter is spelled `psycopg.Connection[tuple[object, ...]]`
rather than bare `psycopg.Connection`. Bare would resolve, via PEP 696, to
psycopg's `TupleRow` default -- which is `tuple[Any, ...]`, i.e. Any straight
into every generated signature. `tuple[object, ...]` is Any-free, and because
psycopg's `Row` TypeVar is covariant an ordinary `psycopg.connect()` result is
still assignable to it.

The cost is that `row[i]` arrives as `object`, so each field is `cast()` to the
type the describe pass reported. That is a feature: every `cast` in the
generated code is one explicit, greppable claim backed by the server's own
RowDescription, and there is no other place where trust enters.

DETERMINISM. Nothing here reads the clock, the DSN, the hostname, the
environment or a set's iteration order. Imports are sorted; queries are emitted
in file order; the only inputs are the .sql text and the server's answers.
"""

from __future__ import annotations

from .annotations import QueryKind
from .describe import Described
from .typemap import JSON_ALIAS

_HEADER = '''"""@generated by altsa_sqlgen from {source} -- DO NOT EDIT.

Nullability below is INFERRED, not declared: for each column the generator
asked PostgreSQL for the base table and attribute behind it
(`pg_attribute.attnotnull`), then patched the answer with what
`EXPLAIN (VERBOSE, FORMAT JSON)` says about outer joins. Columns it could not
attribute to a base table are typed `| None`, which is the safe direction.

{summary}
"""'''


def module_name(stem: str) -> str:
    return stem.replace("-", "_")


def row_class(query_name: str) -> str:
    return "".join(part.title() for part in query_name.split("_")) + "Row"


def render_module(described: list[Described], *, source: str) -> str:
    imports: set[tuple[str, str]] = {("dataclasses", "dataclass")}
    needs_json = False
    for d in described:
        for c in d.columns:
            imports |= c.py.imports
            needs_json |= "JsonValue" in c.py.text
            imports.add(("typing", "cast"))
        for p in d.params:
            imports |= p.py.imports
            needs_json |= "JsonValue" in p.py.text

    lines: list[str] = []
    lines.append(_HEADER.format(source=source, summary=_summary(described)))
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    for module, name in sorted(imports):
        lines.append(f"from {module} import {name}")
    lines.append("")
    lines.append("import psycopg")
    lines.append("")
    lines.append("")
    # NB: this comment must not itself contain the token the leakage check
    # greps for -- see proofs/proof_positive.assert_no_any_in_source.
    lines.append("#: The connection type, spelled without a dynamic row type.")
    lines.append("#: See altsa_sqlgen/emit.py for why it is not bare `Connection`.")
    lines.append("_Conn = psycopg.Connection[tuple[object, ...]]")
    if needs_json:
        lines.append("")
        lines.append(JSON_ALIAS)

    for d in described:
        lines.append("")
        lines.append("")
        lines.extend(_render_query(d))

    return "\n".join(lines) + "\n"


def _summary(described: list[Described]) -> str:
    out: list[str] = ["Queries in this module:", ""]
    for d in described:
        ret = {"one": "one row or None", "many": "a list of rows", "exec": "a row count"}[
            d.block.kind
        ]
        out.append(f"  * {d.block.name} (:{d.block.kind}) -- returns {ret}")
        for c in d.columns:
            how = {
                "catalog": "pg_attribute.attnotnull",
                "explain": "EXPLAIN outer-join analysis",
                "unknown": "not attributable to a base table -- safe default",
                "override": "explicit override in the .sql source",
            }[c.how]
            mark = "NULL" if c.nullable else "NOT NULL"
            out.append(f"      - {c.field}: {c.py.text}  [{mark} via {how}]")
    return "\n".join(out)


def _render_query(d: Described) -> list[str]:
    block = d.block
    kind: QueryKind = block.kind
    name = block.name
    const = f"_{name.upper()}_SQL"
    lines: list[str] = []

    lines.append(f'{const} = """\\')
    lines.append(block.render_psycopg())
    lines.append('"""')

    if kind != "exec":
        cls = row_class(name)
        lines.append("")
        lines.append("")
        lines.append("@dataclass(frozen=True, slots=True)")
        lines.append(f"class {cls}:")
        lines.append(f'    """One row of `{name}`."""')
        lines.append("")
        for c in d.columns:
            lines.append(f"    {c.field}: {c.py.text}")

    lines.append("")
    lines.append("")
    ret = {"one": f"{row_class(name)} | None", "many": f"list[{row_class(name)}]", "exec": "int"}[
        kind
    ]
    lines.extend(_signature(name, d, ret))
    lines.append(f'    """{_docline(d)}"""')

    lines.append("    with conn.cursor() as cur:")
    lines.extend(_execute_call(const, d))
    if kind == "exec":
        lines.append("        return cur.rowcount")
    elif kind == "one":
        lines.append("        row = cur.fetchone()")
        lines.append("        if row is None:")
        lines.append("            return None")
        lines.extend(_construct(d, indent="        ", prefix="return "))
    else:
        lines.append("        return [")
        lines.extend(_construct(d, indent="            ", prefix="", suffix=""))
        lines.append("            for row in cur.fetchall()")
        lines.append("        ]")
    return lines


_WIDTH = 96


def _signature(name: str, d: Described, ret: str) -> list[str]:
    """One line if it fits inside `_WIDTH`, otherwise one parameter per line."""
    star = ", *" if d.params else ""
    inline = "".join(f", {p.name}: {p.py.text}" for p in d.params)
    one = f"def {name}(conn: _Conn{star}{inline}) -> {ret}:"
    if len(one) <= _WIDTH:
        return [one]
    out = [f"def {name}(", "    conn: _Conn,", "    *,"]
    out.extend(f"    {p.name}: {p.py.text}," for p in d.params)
    out.append(f") -> {ret}:")
    return out


def _execute_call(const: str, d: Described) -> list[str]:
    if not d.params:
        return [f"        cur.execute({const})"]
    inline = "{" + ", ".join(f'"{p.name}": {p.name}' for p in d.params) + "}"
    one = f"        cur.execute({const}, {inline})"
    if len(one) <= _WIDTH:
        return [one]
    out = [f"        cur.execute(", f"            {const},", "            {"]
    out.extend(f'                "{p.name}": {p.name},' for p in d.params)
    out.append("            },")
    out.append("        )")
    return out


def _construct(d: Described, *, indent: str, prefix: str, suffix: str = "") -> list[str]:
    cls = row_class(d.block.name)
    out = [f"{indent}{prefix}{cls}("]
    for i, c in enumerate(d.columns):
        out.append(f"{indent}    {c.field}=cast({c.py.text}, row[{i}]),")
    out.append(f"{indent}){suffix}")
    return out


def _docline(d: Described) -> str:
    kind = d.block.kind
    what = {
        "one": "Fetch at most one row.",
        "many": "Fetch every row.",
        "exec": "Execute; returns the affected row count.",
    }[kind]
    return f"{what} Generated from `-- QUERY {d.block.name} :{kind}`."


def render_package_init(modules: list[str]) -> str:
    lines = [
        '"""@generated by altsa_sqlgen -- DO NOT EDIT."""',
        "",
        "from __future__ import annotations",
        "",
    ]
    for m in sorted(modules):
        lines.append(f"from . import {m} as {m}")
    lines.append("")
    lines.append("__all__ = [")
    for m in sorted(modules):
        lines.append(f'    "{m}",')
    lines.append("]")
    return "\n".join(lines) + "\n"
