"""Regenerate BOTH layers into M5, fresh, against the live M5 database.

    uv run python regen.py --url postgresql://postgres:postgres@localhost:55438/altsa

Layer A's generator wants a SQLAlchemy URL and Layer B's wants a libpq DSN; the
same PostgreSQL connection string works for both once `postgresql+psycopg://`
is put in front of it for SQLAlchemy. That translation is done here, once, and
is friction item F3.

Both generators are IMPORTED from their own milestone trees via `m5link`; no
generator code is copied into M5. What M5 owns is the two config inputs
(`joins.toml`, `queries/*.sql`) and the two output directories.

Also times each run and counts the generated lines -- that is benchmark E2.3.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import m5link  # noqa: F401  -- puts M2 and M3 on sys.path

from altsa_gen.config import load_config
from altsa_gen.frontend import build_schema
from altsa_gen.render import render
from altsa_sqlgen.generate import generate

M5 = m5link.M5_ROOT


def sqlalchemy_url(dsn: str) -> str:
    """libpq DSN -> SQLAlchemy URL. F1: the two layers spell it differently."""
    if dsn.startswith("postgresql+"):
        return dsn
    if dsn.startswith("postgresql://"):
        return "postgresql+psycopg://" + dsn[len("postgresql://") :]
    if dsn.startswith("postgres://"):
        return "postgresql+psycopg://" + dsn[len("postgres://") :]
    raise SystemExit(f"cannot turn {dsn!r} into a SQLAlchemy URL")


def loc(path: Path) -> int:
    return len(path.read_text().splitlines())


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="regen")
    ap.add_argument("--url", required=True, help="libpq DSN of the M5 database")
    ap.add_argument("--repeat", type=int, default=3, help="runs to take a median over")
    ap.add_argument("--timings", type=Path, default=None, help="write JSON timings here")
    args = ap.parse_args(argv)

    out_a = M5 / "generated_a"
    out_b = M5 / "generated_b"
    cfg_path = M5 / "joins.toml"
    queries = M5 / "queries"

    a_times: list[float] = []
    b_times: list[float] = []
    schema = None
    result = None

    for _ in range(args.repeat):
        t0 = time.perf_counter()
        cfg = load_config(cfg_path)
        schema = build_schema(sqlalchemy_url(args.url), cfg)
        code = render(schema)
        out_a.mkdir(parents=True, exist_ok=True)
        (out_a / "__init__.py").write_text(
            '"""GENERATED by altsa_gen (M2) into M5 -- DO NOT EDIT."""\n'
        )
        (out_a / f"{cfg.module}.py").write_text(code)
        a_times.append(time.perf_counter() - t0)

        t0 = time.perf_counter()
        result = generate(url=args.url, queries=queries, out=out_b)
        b_times.append(time.perf_counter() - t0)

    assert schema is not None and result is not None

    def median(xs: list[float]) -> float:
        s = sorted(xs)
        return s[len(s) // 2]

    facade = out_a / "facade.py"
    b_files = sorted(p for p in out_b.glob("*.py"))
    a_loc = loc(facade)
    b_loc = sum(loc(p) for p in b_files)

    print("Layer A (altsa_gen, M2)")
    print(f"  tables {len(schema.tables)}  enums {len(schema.enums)}  "
          f"edges {len(schema.edges)}  shapes {len(schema.shapes)}  "
          f"projections {len(schema.projections)}")
    print(f"  {facade.relative_to(M5)}: {a_loc} lines")
    print(f"  median of {args.repeat} full runs: {median(a_times) * 1000:.0f} ms  "
          f"(all: {', '.join(f'{t * 1000:.0f}' for t in a_times)} ms)")
    print()
    print("Layer B (altsa_sqlgen, M3)")
    print(f"  {len(result.described)} queries in {len(result.modules)} modules, "
          f"{sum(len(d.columns) for d in result.described)} result columns")
    for p in b_files:
        print(f"  generated_b/{p.name}: {loc(p)} lines")
    print(f"  total: {b_loc} lines")
    print(f"  median of {args.repeat} full runs: {median(b_times) * 1000:.0f} ms  "
          f"(all: {', '.join(f'{t * 1000:.0f}' for t in b_times)} ms)")
    print()
    print(f"input LOC: joins.toml {loc(cfg_path)}, "
          f"queries/*.sql {sum(loc(p) for p in sorted(queries.glob('*.sql')))}")

    if args.timings is not None:
        args.timings.write_text(
            json.dumps(
                {
                    "layer_a_ms": [t * 1000 for t in a_times],
                    "layer_a_median_ms": median(a_times) * 1000,
                    "layer_a_loc": a_loc,
                    "layer_a_shapes": len(schema.shapes),
                    "layer_b_ms": [t * 1000 for t in b_times],
                    "layer_b_median_ms": median(b_times) * 1000,
                    "layer_b_loc": b_loc,
                    "layer_b_queries": len(result.described),
                    "joins_toml_loc": loc(cfg_path),
                    "queries_sql_loc": sum(loc(p) for p in sorted(queries.glob("*.sql"))),
                },
                indent=2,
            )
            + "\n"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
