-- PostgreSQL 16 OLTP schema for the sqlacodegen trial.
-- Deliberately exercises interesting type-mapping cases:
--   uuid + gen_random_uuid(), native ENUM types, numeric(10,2), jsonb,
--   text[], timestamptz, identity columns, composite PK, CHECK-based
--   discriminator, and shared-PK ("joined table") inheritance.

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid() is builtin in PG13+, kept for safety

-- ---------------------------------------------------------------- enums
CREATE TYPE user_status  AS ENUM ('active', 'suspended', 'deleted');
CREATE TYPE order_status AS ENUM ('pending', 'paid', 'shipped', 'cancelled');

-- ---------------------------------------------------------------- users
CREATE TABLE users (
    id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    email      text        NOT NULL UNIQUE,
    status     user_status NOT NULL DEFAULT 'active',
    metadata   jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------- products
CREATE TABLE products (
    id    bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku   text          NOT NULL UNIQUE,
    name  varchar(200)  NOT NULL,
    price numeric(10,2) NOT NULL CONSTRAINT products_price_nonneg CHECK (price >= 0),
    tags  text[],
    stock integer       NOT NULL DEFAULT 0
);

-- --------------------------------------------------------------- orders
CREATE TABLE orders (
    id         uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    uuid         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status     order_status NOT NULL DEFAULT 'pending',
    version    integer      NOT NULL DEFAULT 1,           -- optimistic locking
    total      numeric(12,2) NOT NULL DEFAULT 0,
    created_at timestamptz  NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------- order_items
CREATE TABLE order_items (
    order_id   uuid          NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id bigint        NOT NULL REFERENCES products(id),
    quantity   integer       NOT NULL CONSTRAINT order_items_qty_pos CHECK (quantity > 0),
    unit_price numeric(10,2) NOT NULL,
    PRIMARY KEY (order_id, product_id)
);

-- ------------------------------------------------------------- payments
-- Discriminator / "polymorphic" case: a `method` column plus per-method
-- nullable columns. The ORM cannot infer single-table inheritance from this.
CREATE TABLE payments (
    id              bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        uuid          NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
    method          text          NOT NULL
                    CONSTRAINT payments_method_check CHECK (method IN ('card','bank','wallet')),
    amount          numeric(12,2) NOT NULL,
    card_last4      char(4),
    bank_account    text,
    wallet_provider text,
    paid_at         timestamptz   NOT NULL DEFAULT now()
);

-- -------------------------------------------- shared-PK inheritance case
CREATE TABLE accounts (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       text        NOT NULL DEFAULT 'basic',
    label      text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- PK is also the FK to accounts.id -> classic "joined table inheritance" shape.
CREATE TABLE staff_accounts (
    id          bigint  PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
    employee_no text    NOT NULL UNIQUE,
    department  text    NOT NULL
);

-- -------------------------------------------------------------- indexes
CREATE INDEX orders_user_created_idx  ON orders (user_id, created_at DESC);
CREATE INDEX orders_status_idx        ON orders (status);
CREATE INDEX order_items_product_idx  ON order_items (product_id);
CREATE INDEX products_tags_gin        ON products USING gin (tags);
CREATE INDEX users_metadata_gin       ON users USING gin (metadata);
