-- Reproduces sqlacodegen's known "unmappable type" behaviour: a Postgres
-- composite type used as a column type. Deliberately kept in its own schema
-- (`demo`) so it does not contaminate the main trial schema.

DROP SCHEMA IF EXISTS demo CASCADE;
CREATE SCHEMA demo;

CREATE TYPE demo.address AS (
    street text,
    city   text,
    zip    text
);

CREATE TABLE demo.warehouses (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     text   NOT NULL,
    location demo.address           -- <- composite type column
);
