"""@generated by altsa_sqlgen -- DO NOT EDIT."""

from __future__ import annotations

from . import orders as orders
from . import products as products
from . import users as users

__all__ = [
    "orders",
    "products",
    "users",
]
