"""@generated by altsa_sqlgen from orders.sql -- DO NOT EDIT.

Nullability below is INFERRED, not declared: for each column the generator
asked PostgreSQL for the base table and attribute behind it
(`pg_attribute.attnotnull`), then patched the answer with what
`EXPLAIN (VERBOSE, FORMAT JSON)` says about outer joins. Columns it could not
attribute to a base table are typed `| None`, which is the safe direction.

Queries in this module:

  * insert_order (:one) -- returns one row or None
      - id: UUID  [NOT NULL via pg_attribute.attnotnull]
      - user_id: UUID  [NOT NULL via pg_attribute.attnotnull]
      - status: str  [NOT NULL via pg_attribute.attnotnull]
      - version: int  [NOT NULL via pg_attribute.attnotnull]
      - total: Decimal  [NOT NULL via pg_attribute.attnotnull]
      - created_at: datetime  [NOT NULL via pg_attribute.attnotnull]
  * insert_order_item (:exec) -- returns a row count
  * set_order_total (:exec) -- returns a row count
  * record_payment (:one) -- returns one row or None
      - id: int  [NOT NULL via pg_attribute.attnotnull]
      - order_id: UUID  [NOT NULL via pg_attribute.attnotnull]
      - method: str  [NOT NULL via pg_attribute.attnotnull]
      - amount: Decimal  [NOT NULL via pg_attribute.attnotnull]
      - paid_at: datetime  [NOT NULL via pg_attribute.attnotnull]
  * transition_order_status (:one) -- returns one row or None
      - id: UUID  [NOT NULL via pg_attribute.attnotnull]
      - status: str  [NOT NULL via pg_attribute.attnotnull]
      - version: int  [NOT NULL via pg_attribute.attnotnull]
      - total: Decimal  [NOT NULL via pg_attribute.attnotnull]
      - created_at: datetime  [NOT NULL via pg_attribute.attnotnull]
  * get_order_with_user (:one) -- returns one row or None
      - id: UUID  [NOT NULL via pg_attribute.attnotnull]
      - status: str  [NOT NULL via pg_attribute.attnotnull]
      - total: Decimal  [NOT NULL via pg_attribute.attnotnull]
      - version: int  [NOT NULL via pg_attribute.attnotnull]
      - created_at: datetime  [NOT NULL via pg_attribute.attnotnull]
      - user_id: UUID  [NOT NULL via pg_attribute.attnotnull]
      - email: str  [NOT NULL via pg_attribute.attnotnull]
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from typing import cast
from uuid import UUID

import psycopg


#: The connection type, spelled without a dynamic row type.
#: See altsa_sqlgen/emit.py for why it is not bare `Connection`.
_Conn = psycopg.Connection[tuple[object, ...]]


_INSERT_ORDER_SQL = """\
INSERT INTO orders (user_id)
VALUES (%(user_id)s)
RETURNING id, user_id, status, version, total, created_at
"""


@dataclass(frozen=True, slots=True)
class InsertOrderRow:
    """One row of `insert_order`."""

    id: UUID
    user_id: UUID
    status: str
    version: int
    total: Decimal
    created_at: datetime


def insert_order(conn: _Conn, *, user_id: UUID) -> InsertOrderRow | None:
    """Fetch at most one row. Generated from `-- QUERY insert_order :one`."""
    with conn.cursor() as cur:
        cur.execute(_INSERT_ORDER_SQL, {"user_id": user_id})
        row = cur.fetchone()
        if row is None:
            return None
        return InsertOrderRow(
            id=cast(UUID, row[0]),
            user_id=cast(UUID, row[1]),
            status=cast(str, row[2]),
            version=cast(int, row[3]),
            total=cast(Decimal, row[4]),
            created_at=cast(datetime, row[5]),
        )


_INSERT_ORDER_ITEM_SQL = """\
INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (%(order_id)s, %(product_id)s, %(quantity)s, %(unit_price)s)
"""


def insert_order_item(
    conn: _Conn,
    *,
    order_id: UUID,
    product_id: int,
    quantity: int,
    unit_price: Decimal,
) -> int:
    """Execute; returns the affected row count. Generated from `-- QUERY insert_order_item :exec`."""
    with conn.cursor() as cur:
        cur.execute(
            _INSERT_ORDER_ITEM_SQL,
            {
                "order_id": order_id,
                "product_id": product_id,
                "quantity": quantity,
                "unit_price": unit_price,
            },
        )
        return cur.rowcount


_SET_ORDER_TOTAL_SQL = """\
UPDATE orders
SET total = %(total)s
WHERE id = %(order_id)s
"""


def set_order_total(conn: _Conn, *, total: Decimal, order_id: UUID) -> int:
    """Execute; returns the affected row count. Generated from `-- QUERY set_order_total :exec`."""
    with conn.cursor() as cur:
        cur.execute(_SET_ORDER_TOTAL_SQL, {"total": total, "order_id": order_id})
        return cur.rowcount


_RECORD_PAYMENT_SQL = """\
INSERT INTO payments (order_id, method, amount, card_last4)
VALUES (%(order_id)s, %(method)s, %(amount)s, %(card_last4)s)
RETURNING id, order_id, method, amount, paid_at
"""


@dataclass(frozen=True, slots=True)
class RecordPaymentRow:
    """One row of `record_payment`."""

    id: int
    order_id: UUID
    method: str
    amount: Decimal
    paid_at: datetime


def record_payment(
    conn: _Conn,
    *,
    order_id: UUID,
    method: str,
    amount: Decimal,
    card_last4: str | None,
) -> RecordPaymentRow | None:
    """Fetch at most one row. Generated from `-- QUERY record_payment :one`."""
    with conn.cursor() as cur:
        cur.execute(
            _RECORD_PAYMENT_SQL,
            {
                "order_id": order_id,
                "method": method,
                "amount": amount,
                "card_last4": card_last4,
            },
        )
        row = cur.fetchone()
        if row is None:
            return None
        return RecordPaymentRow(
            id=cast(int, row[0]),
            order_id=cast(UUID, row[1]),
            method=cast(str, row[2]),
            amount=cast(Decimal, row[3]),
            paid_at=cast(datetime, row[4]),
        )


_TRANSITION_ORDER_STATUS_SQL = """\
UPDATE orders
SET status  = %(new_status)s,
    version = version + 1
WHERE id = %(order_id)s
  AND version = %(expected_version)s
RETURNING id, status, version, total, created_at
"""


@dataclass(frozen=True, slots=True)
class TransitionOrderStatusRow:
    """One row of `transition_order_status`."""

    id: UUID
    status: str
    version: int
    total: Decimal
    created_at: datetime


def transition_order_status(
    conn: _Conn,
    *,
    new_status: str,
    order_id: UUID,
    expected_version: int,
) -> TransitionOrderStatusRow | None:
    """Fetch at most one row. Generated from `-- QUERY transition_order_status :one`."""
    with conn.cursor() as cur:
        cur.execute(
            _TRANSITION_ORDER_STATUS_SQL,
            {
                "new_status": new_status,
                "order_id": order_id,
                "expected_version": expected_version,
            },
        )
        row = cur.fetchone()
        if row is None:
            return None
        return TransitionOrderStatusRow(
            id=cast(UUID, row[0]),
            status=cast(str, row[1]),
            version=cast(int, row[2]),
            total=cast(Decimal, row[3]),
            created_at=cast(datetime, row[4]),
        )


_GET_ORDER_WITH_USER_SQL = """\
SELECT o.id,
       o.status,
       o.total,
       o.version,
       o.created_at,
       u.id      AS user_id,
       u.email
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE o.id = %(order_id)s
"""


@dataclass(frozen=True, slots=True)
class GetOrderWithUserRow:
    """One row of `get_order_with_user`."""

    id: UUID
    status: str
    total: Decimal
    version: int
    created_at: datetime
    user_id: UUID
    email: str


def get_order_with_user(conn: _Conn, *, order_id: UUID) -> GetOrderWithUserRow | None:
    """Fetch at most one row. Generated from `-- QUERY get_order_with_user :one`."""
    with conn.cursor() as cur:
        cur.execute(_GET_ORDER_WITH_USER_SQL, {"order_id": order_id})
        row = cur.fetchone()
        if row is None:
            return None
        return GetOrderWithUserRow(
            id=cast(UUID, row[0]),
            status=cast(str, row[1]),
            total=cast(Decimal, row[2]),
            version=cast(int, row[3]),
            created_at=cast(datetime, row[4]),
            user_id=cast(UUID, row[5]),
            email=cast(str, row[6]),
        )
