"""@generated by altsa_sqlgen from products.sql -- DO NOT EDIT.

Nullability below is INFERRED, not declared: for each column the generator
asked PostgreSQL for the base table and attribute behind it
(`pg_attribute.attnotnull`), then patched the answer with what
`EXPLAIN (VERBOSE, FORMAT JSON)` says about outer joins. Columns it could not
attribute to a base table are typed `| None`, which is the safe direction.

Queries in this module:

  * upsert_product (:one) -- returns one row or None
      - id: int  [NOT NULL via pg_attribute.attnotnull]
      - sku: str  [NOT NULL via pg_attribute.attnotnull]
      - name: str  [NOT NULL via pg_attribute.attnotnull]
      - price: Decimal  [NOT NULL via pg_attribute.attnotnull]
      - tags: list[str | None] | None  [NULL via pg_attribute.attnotnull]
      - stock: int  [NOT NULL via pg_attribute.attnotnull]
  * lock_products_for_update (:many) -- returns a list of rows
      - id: int  [NOT NULL via pg_attribute.attnotnull]
      - sku: str  [NOT NULL via pg_attribute.attnotnull]
      - name: str  [NOT NULL via pg_attribute.attnotnull]
      - price: Decimal  [NOT NULL via pg_attribute.attnotnull]
      - tags: list[str | None] | None  [NULL via pg_attribute.attnotnull]
      - stock: int  [NOT NULL via pg_attribute.attnotnull]
  * decrement_stock (:one) -- returns one row or None
      - id: int  [NOT NULL via pg_attribute.attnotnull]
      - sku: str  [NOT NULL via pg_attribute.attnotnull]
      - price: Decimal  [NOT NULL via pg_attribute.attnotnull]
      - stock: int  [NOT NULL via pg_attribute.attnotnull]
  * get_product_by_sku (:one) -- returns one row or None
      - id: int  [NOT NULL via pg_attribute.attnotnull]
      - sku: str  [NOT NULL via pg_attribute.attnotnull]
      - name: str  [NOT NULL via pg_attribute.attnotnull]
      - price: Decimal  [NOT NULL via pg_attribute.attnotnull]
      - stock: int  [NOT NULL via pg_attribute.attnotnull]
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from typing import cast

import psycopg


#: The connection type, spelled without a dynamic row type.
#: See altsa_sqlgen/emit.py for why it is not bare `Connection`.
_Conn = psycopg.Connection[tuple[object, ...]]


_UPSERT_PRODUCT_SQL = """\
INSERT INTO products (sku, name, price, tags, stock)
VALUES (%(sku)s, %(name)s, %(price)s, %(tags)s, %(stock)s)
ON CONFLICT (sku) DO UPDATE
    SET name  = EXCLUDED.name,
        price = EXCLUDED.price,
        tags  = EXCLUDED.tags,
        stock = products.stock + EXCLUDED.stock
RETURNING id, sku, name, price, tags, stock
"""


@dataclass(frozen=True, slots=True)
class UpsertProductRow:
    """One row of `upsert_product`."""

    id: int
    sku: str
    name: str
    price: Decimal
    tags: list[str | None] | None
    stock: int


def upsert_product(
    conn: _Conn,
    *,
    sku: str,
    name: str,
    price: Decimal,
    tags: list[str | None],
    stock: int,
) -> UpsertProductRow | None:
    """Fetch at most one row. Generated from `-- QUERY upsert_product :one`."""
    with conn.cursor() as cur:
        cur.execute(
            _UPSERT_PRODUCT_SQL,
            {
                "sku": sku,
                "name": name,
                "price": price,
                "tags": tags,
                "stock": stock,
            },
        )
        row = cur.fetchone()
        if row is None:
            return None
        return UpsertProductRow(
            id=cast(int, row[0]),
            sku=cast(str, row[1]),
            name=cast(str, row[2]),
            price=cast(Decimal, row[3]),
            tags=cast(list[str | None] | None, row[4]),
            stock=cast(int, row[5]),
        )


_LOCK_PRODUCTS_FOR_UPDATE_SQL = """\
SELECT id, sku, name, price, tags, stock
FROM products
WHERE sku = ANY(%(skus)s)
ORDER BY sku
FOR UPDATE
"""


@dataclass(frozen=True, slots=True)
class LockProductsForUpdateRow:
    """One row of `lock_products_for_update`."""

    id: int
    sku: str
    name: str
    price: Decimal
    tags: list[str | None] | None
    stock: int


def lock_products_for_update(
    conn: _Conn,
    *,
    skus: list[str | None],
) -> list[LockProductsForUpdateRow]:
    """Fetch every row. Generated from `-- QUERY lock_products_for_update :many`."""
    with conn.cursor() as cur:
        cur.execute(_LOCK_PRODUCTS_FOR_UPDATE_SQL, {"skus": skus})
        return [
            LockProductsForUpdateRow(
                id=cast(int, row[0]),
                sku=cast(str, row[1]),
                name=cast(str, row[2]),
                price=cast(Decimal, row[3]),
                tags=cast(list[str | None] | None, row[4]),
                stock=cast(int, row[5]),
            )
            for row in cur.fetchall()
        ]


_DECREMENT_STOCK_SQL = """\
UPDATE products
SET stock = stock - %(quantity)s
WHERE id = %(product_id)s
  AND stock >= %(quantity)s
RETURNING id, sku, price, stock
"""


@dataclass(frozen=True, slots=True)
class DecrementStockRow:
    """One row of `decrement_stock`."""

    id: int
    sku: str
    price: Decimal
    stock: int


def decrement_stock(conn: _Conn, *, quantity: int, product_id: int) -> DecrementStockRow | None:
    """Fetch at most one row. Generated from `-- QUERY decrement_stock :one`."""
    with conn.cursor() as cur:
        cur.execute(_DECREMENT_STOCK_SQL, {"quantity": quantity, "product_id": product_id})
        row = cur.fetchone()
        if row is None:
            return None
        return DecrementStockRow(
            id=cast(int, row[0]),
            sku=cast(str, row[1]),
            price=cast(Decimal, row[2]),
            stock=cast(int, row[3]),
        )


_GET_PRODUCT_BY_SKU_SQL = """\
SELECT id, sku, name, price, stock
FROM products
WHERE sku = %(sku)s
"""


@dataclass(frozen=True, slots=True)
class GetProductBySkuRow:
    """One row of `get_product_by_sku`."""

    id: int
    sku: str
    name: str
    price: Decimal
    stock: int


def get_product_by_sku(conn: _Conn, *, sku: str) -> GetProductBySkuRow | None:
    """Fetch at most one row. Generated from `-- QUERY get_product_by_sku :one`."""
    with conn.cursor() as cur:
        cur.execute(_GET_PRODUCT_BY_SKU_SQL, {"sku": sku})
        row = cur.fetchone()
        if row is None:
            return None
        return GetProductBySkuRow(
            id=cast(int, row[0]),
            sku=cast(str, row[1]),
            name=cast(str, row[2]),
            price=cast(Decimal, row[3]),
            stock=cast(int, row[4]),
        )
