"""@generated by altsa_sqlgen from users.sql -- DO NOT EDIT.

Nullability below is INFERRED, not declared: for each column the generator
asked PostgreSQL for the base table and attribute behind it
(`pg_attribute.attnotnull`), then patched the answer with what
`EXPLAIN (VERBOSE, FORMAT JSON)` says about outer joins. Columns it could not
attribute to a base table are typed `| None`, which is the safe direction.

Queries in this module:

  * register_user (:one) -- returns one row or None
      - id: UUID  [NOT NULL via pg_attribute.attnotnull]
      - email: str  [NOT NULL via pg_attribute.attnotnull]
      - status: str  [NOT NULL via pg_attribute.attnotnull]
      - created_at: datetime  [NOT NULL via pg_attribute.attnotnull]
  * get_user_by_email (:one) -- returns one row or None
      - id: UUID  [NOT NULL via pg_attribute.attnotnull]
      - email: str  [NOT NULL via pg_attribute.attnotnull]
      - status: str  [NOT NULL via pg_attribute.attnotnull]
      - created_at: datetime  [NOT NULL via pg_attribute.attnotnull]
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import cast
from uuid import UUID

import psycopg


#: The connection type, spelled without a dynamic row type.
#: See altsa_sqlgen/emit.py for why it is not bare `Connection`.
_Conn = psycopg.Connection[tuple[object, ...]]


_REGISTER_USER_SQL = """\
INSERT INTO users (email, status)
VALUES (%(email)s, %(status)s)
RETURNING id, email, status, created_at
"""


@dataclass(frozen=True, slots=True)
class RegisterUserRow:
    """One row of `register_user`."""

    id: UUID
    email: str
    status: str
    created_at: datetime


def register_user(conn: _Conn, *, email: str, status: str) -> RegisterUserRow | None:
    """Fetch at most one row. Generated from `-- QUERY register_user :one`."""
    with conn.cursor() as cur:
        cur.execute(_REGISTER_USER_SQL, {"email": email, "status": status})
        row = cur.fetchone()
        if row is None:
            return None
        return RegisterUserRow(
            id=cast(UUID, row[0]),
            email=cast(str, row[1]),
            status=cast(str, row[2]),
            created_at=cast(datetime, row[3]),
        )


_GET_USER_BY_EMAIL_SQL = """\
SELECT id, email, status, created_at
FROM users
WHERE email = %(email)s
"""


@dataclass(frozen=True, slots=True)
class GetUserByEmailRow:
    """One row of `get_user_by_email`."""

    id: UUID
    email: str
    status: str
    created_at: datetime


def get_user_by_email(conn: _Conn, *, email: str) -> GetUserByEmailRow | None:
    """Fetch at most one row. Generated from `-- QUERY get_user_by_email :one`."""
    with conn.cursor() as cur:
        cur.execute(_GET_USER_BY_EMAIL_SQL, {"email": email})
        row = cur.fetchone()
        if row is None:
            return None
        return GetUserByEmailRow(
            id=cast(UUID, row[0]),
            email=cast(str, row[1]),
            status=cast(str, row[2]),
            created_at=cast(datetime, row[3]),
        )
