-- Probe schema: everything the catalog loader is expected to handle, plus a
-- deliberate tail of things it is not, so the warning list in the report is
-- measured rather than asserted.

-- ---- supported --------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS probe;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
CREATE DOMAIN positive_int AS integer CHECK (VALUE > 0);
CREATE SEQUENCE thing_seq;

CREATE TABLE base (
    id         serial PRIMARY KEY,
    big        bigserial,
    ident      bigint      GENERATED BY DEFAULT AS IDENTITY,
    always     bigint      GENERATED ALWAYS AS IDENTITY,
    required   text        NOT NULL,
    optional   text,
    enum_col   mood        NOT NULL DEFAULT 'ok',
    checked    numeric(10,2) CONSTRAINT base_checked_pos CHECK (checked >= 0),
    computed   numeric     GENERATED ALWAYS AS (checked * 2) STORED,
    uniq       text        UNIQUE,
    arr        text[],
    js         jsonb
);

CREATE TABLE composite_pk (
    left_id  integer,
    right_id integer,
    payload  text,
    PRIMARY KEY (left_id, right_id)
);

CREATE TABLE child (
    id     integer PRIMARY KEY,
    parent integer REFERENCES base(id) ON DELETE CASCADE,
    note   text
);

ALTER TABLE child ADD COLUMN added_required text NOT NULL DEFAULT 'x';
ALTER TABLE child ADD COLUMN added_optional text;
ALTER TABLE child ALTER COLUMN note SET NOT NULL;
ALTER TABLE child ALTER COLUMN added_optional DROP NOT NULL;
ALTER TABLE child ADD CONSTRAINT child_uq UNIQUE (note);
ALTER TABLE child DROP COLUMN added_optional;

CREATE INDEX child_note_idx ON child (note);
COMMENT ON TABLE child IS 'a child';
GRANT SELECT ON child TO PUBLIC;

-- ---- NOT supported: each of these should produce a warning, not a crash ---
CREATE VIEW child_view AS SELECT id, note FROM child;
CREATE MATERIALIZED VIEW child_mv AS SELECT id FROM child;
CREATE TABLE from_query AS SELECT id FROM child;
CREATE TABLE inherited (LIKE base INCLUDING ALL);
CREATE UNLOGGED TABLE partitioned (id integer NOT NULL, at date NOT NULL)
    PARTITION BY RANGE (at);
CREATE FOREIGN TABLE ft (id integer) SERVER nowhere;
ALTER TABLE nonexistent ADD COLUMN x integer;
