"""The renderer: GSchema -> one Python module.

Written from scratch against the model graph; none of sqlacodegen's `render_*`
methods are used (they emit SQLAlchemy models, which is the thing this project
exists not to hand to callers).

Determinism rules obeyed here:
  * no timestamps, no database URL, no host names in the output
  * every dict is walked in sorted order; every list arrives pre-sorted from
    `frontend.build_schema`
  * column order is the table's own ordinal order, which reflection preserves
"""

from __future__ import annotations

from keyword import iskeyword

from .gir import GColumn, GSchema, GShape, GTable

_RUNTIME_REEXPORTS = (
    "Assign",
    "Col",
    "Conn",
    "Expr",
    "NumCol",
    "Order",
    "Pred",
    "Projection",
    "Raw",
    "Select",
    "all_of",
    "any_of",
    "coalesce",
    "count_",
    "count_star",
    "max_",
    "min_",
    "not_",
    "sum_",
)

_HEADER = '''"""GENERATED by altsa_gen -- DO NOT EDIT.

The typed SQL facade for this schema. Nothing in the public surface mentions
SQLAlchemy: every SQLAlchemy import in the project lives in
`altsa_runtime._backend`, which this module never touches directly.

What is here (SCHEMA-DEPENDENT):
  * one Python enum per database enum / CHECK-derived enum
  * the catalog registration the runtime executes against
  * one `_XxxCols` and one `_XxxColsN` namespace per table -- `ColsN` is the
    pre-computed `Nullable<Cols>` a LEFT JOIN puts you in
  * one `Q...` class per REACHABLE JOIN SHAPE, carrying exactly the aliases
    that shape makes visible, in exactly the nullability state it implies
  * one typed combinator per DECLARED edge, per join kind
  * typed INSERT / UPDATE / DELETE helpers per table

What is NOT here (SCHEMA-INDEPENDENT, imported from `altsa_runtime`):
  `Col`/`NumCol`/`Expr`/`Pred` and their operators, `all_of`/`any_of`,
  aggregates, `Conn`, the shape-memoised execution path, and the 13 `select()`
  overloads -- pure arity machinery that never names a table.

Dialect reflected: {dialect}
"""'''


def _ident(name: str) -> str:
    return f"{name}_" if iskeyword(name) else name


def _col_expr(col: GColumn, table: str, tag: str, nullable: bool) -> str:
    cls = "NumCol" if col.numeric else "Col"
    py = col.py_type
    if nullable or not col.not_null:
        py = f"{py} | None"
    return (
        f"    {_ident(col.name)}: {cls}[{tag}, {py}] = "
        f'{cls}("{table}", "{col.name}")'
    )


def _column_spec(col: GColumn) -> str:
    parts = [
        f'name="{col.name}"',
        f'kind="{col.kind}"',
        f"not_null={col.not_null}",
    ]
    if col.primary_key:
        parts.append("primary_key=True")
    if col.length is not None:
        parts.append(f"length={col.length}")
    if col.precision is not None:
        parts.append(f"precision={col.precision}")
    if col.scale is not None:
        parts.append(f"scale={col.scale}")
    if col.enum_name is not None:
        parts.append(f'enum_name="{col.enum_name}"')
    if col.enum_values:
        vals = ", ".join(f'"{v}"' for v in col.enum_values)
        parts.append(f"enum_values=({vals},)")
    if col.item_kind is not None:
        parts.append(f'item_kind="{col.item_kind}"')
    if col.has_default:
        parts.append("has_default=True")
    return "ColumnSpec(" + ", ".join(parts) + ")"


def _combinators(schema: GSchema, shape: GShape) -> list[str]:
    """One method per (edge, kind) whose resulting shape actually exists."""
    present = [shape.root, *[s.target for s in shape.steps]]
    by_key = {s.key: s for s in schema.shapes}
    out: list[str] = []
    for edge in schema.edges:
        if edge.frm not in present or edge.to in present:
            continue
        for kind, prefix in (("inner", "join"), ("left", "left_join")):
            key = (
                shape.root,
                (*[(s.edge, s.kind) for s in shape.steps], (edge.id, kind)),
            )
            target_shape = by_key.get(key)
            if target_shape is None:
                continue
            out.append(
                f"    def {prefix}_{edge.method_suffix}(self) -> "
                f"{target_shape.class_name}:\n"
                f"        return {target_shape.class_name}(\n"
                f'            self.plan().with_join("{edge.id}", "{edge.to}", "{kind}")\n'
                f"        )"
            )
    return out


def _insert_fn(table: GTable) -> str:
    lines = [f"def insert_{table.name}(", "    conn: Conn,", "    *,"]
    body: list[str] = ['    _values: dict[str, object] = {}']
    for col in table.columns:
        ident = _ident(col.name)
        if col.not_null and not col.has_default:
            lines.append(f"    {ident}: {col.py_type},")
            body.append(f'    _values["{col.name}"] = {ident}')
            continue
        if col.not_null:
            lines.append(f"    {ident}: {col.py_type} | Unset = UNSET,")
        else:
            lines.append(f"    {ident}: {col.py_type} | None | Unset = UNSET,")
        body.append(f"    if not isinstance({ident}, Unset):")
        body.append(f'        _values["{col.name}"] = {ident}')
    lines.append(") -> int:")
    lines.append(f'    """Typed INSERT. Columns with a server default may be omitted."""')
    lines.extend(body)
    lines.append(f'    return conn.insert_values("{table.name}", _values)')
    return "\n".join(lines)


def render(schema: GSchema) -> str:
    used_py = {c.py_type for t in schema.tables for c in t.columns}
    used_py |= {f.py_type for p in schema.projections for f in p.fields}
    joined = " ".join(used_py)

    out: list[str] = [_HEADER.format(dialect=schema.dialect), ""]
    out.append("from __future__ import annotations")
    out.append("")

    std: list[str] = []
    if "_dt." in joined:
        std.append("import datetime as _dt")
    if schema.enums:
        std.append("import enum")
    out.extend(sorted(std))
    if std:
        out.append("")
    frm: list[str] = []
    if schema.projections:
        frm.append("from dataclasses import dataclass")
    if "Decimal" in joined:
        frm.append("from decimal import Decimal")
    frm.append("from typing import Literal, final")
    if "UUID" in joined:
        frm.append("from uuid import UUID")
    out.extend(frm)
    out.append("")

    out.append("from altsa_runtime import (")
    for name in _RUNTIME_REEXPORTS:
        out.append(f"    {name},")
    out.append(")")
    out.append("from altsa_runtime.catalog import (")
    for name in (
        "ColumnSpec",
        "EdgeSpec",
        "TableSpec",
        "register_edge",
        "register_enum",
        "register_table",
    ):
        out.append(f"    {name},")
    out.append(")")
    out.append("from altsa_runtime.ir import Plan as _Plan")
    out.append("from altsa_runtime.query import QueryBase as _QueryBase")
    out.append("from altsa_runtime.sentinel import UNSET, Unset")
    out.append("")

    # ---- __all__ -----------------------------------------------------------
    exported = set(_RUNTIME_REEXPORTS)
    exported |= {e.class_name for e in schema.enums}
    exported |= {t.const for t in schema.tables}
    exported |= {s.class_name for s in schema.shapes}
    exported |= {p.row_class for p in schema.projections}
    exported |= {f"from_{t.name}" for t in schema.tables}
    for t in schema.tables:
        exported |= {f"insert_{t.name}", f"update_{t.name}", f"delete_{t.name}"}
    out.append("__all__ = [")
    for name in sorted(exported):
        out.append(f'    "{name}",')
    out.append("]")
    out.append("")

    # ---- 1. enums ----------------------------------------------------------
    if schema.enums:
        out.append(_rule("1. generated enums (database ENUM / CHECK -> Python enum)"))
        for en in schema.enums:
            origin = (
                f"native PostgreSQL type {en.db_name!r}"
                if en.native
                else "derived from a CHECK constraint"
            )
            out.append(f"class {en.class_name}(str, enum.Enum):")
            out.append(f'    """{origin}."""')
            out.append("")
            for m in en.members:
                out.append(f'    {m.name} = "{m.value}"')
            out.append("")
            out.append("")

    # ---- 2. catalog registration ------------------------------------------
    out.append(_rule("2. catalog registration -- what the runtime executes against"))
    for t in schema.tables:
        out.append("register_table(")
        out.append("    TableSpec(")
        out.append(f'        "{t.name}",')
        out.append("        (")
        for c in t.columns:
            out.append(f"            {_column_spec(c)},")
        out.append("        ),")
        out.append("    )")
        out.append(")")
    out.append("")
    for e in schema.edges:
        pairs = ", ".join(
            "(" + ", ".join(f'"{x}"' for x in quad) + ")" for quad in e.on
        )
        out.append(
            f'register_edge(EdgeSpec("{e.id}", "{e.frm}", "{e.to}", ({pairs},)))'
        )
    out.append("")
    enum_regs: list[str] = []
    for t in schema.tables:
        for c in t.columns:
            if c.kind == "enum":
                enum_regs.append(
                    f'register_enum("{t.name}", "{c.name}", {c.py_type})'
                )
    out.extend(sorted(enum_regs))
    out.append("")
    out.append("")

    # ---- 3. column namespaces ---------------------------------------------
    out.append(
        _rule(
            "3. column namespaces -- normal and Nullable variants.\n"
            "# `_XxxColsN` is the pre-computed `Nullable<_XxxCols>`. Kysely recomputes\n"
            "# this on every type-check with a mapped type; here the generator wrote it\n"
            "# out once. The classes are stateless, so one module-level instance is\n"
            "# shared by every query."
        )
    )
    for t in schema.tables:
        out.append(f'{t.tag} = Literal["{t.name}"]')
    out.append("")
    out.append("")
    for t in schema.tables:
        out.append("@final")
        out.append(f"class {t.cols_class}:")
        out.append("    __slots__ = ()")
        for c in t.columns:
            out.append(_col_expr(c, t.name, t.tag, nullable=False))
        out.append("")
        out.append("")
        out.append("@final")
        out.append(f"class {t.cols_n_class}:")
        out.append("    __slots__ = ()")
        for c in t.columns:
            out.append(_col_expr(c, t.name, t.tag, nullable=True))
        out.append("")
        out.append("")
    for t in schema.tables:
        out.append(f"{t.const} = {t.cols_class}()")
    out.append("")
    for t in schema.tables:
        out.append(f"{t.const_n} = {t.cols_n_class}()")
    out.append("")
    out.append("")

    # ---- 4. declared projection row types ---------------------------------
    if schema.projections:
        out.append(_rule("4. declared projection row types"))
        for p in schema.projections:
            out.append("@dataclass(frozen=True, slots=True)")
            out.append(f"class {p.row_class}:")
            out.append(
                f'    """Declared projection, emitted only on shape '
                f'`{p.shape_class}`."""'
            )
            out.append("")
            for f in p.fields:
                out.append(f"    {_ident(f.field)}: {f.py_type}")
            out.append("")
            out.append("")

    # ---- 5. query shapes ---------------------------------------------------
    out.append(
        _rule(
            "5. query shapes.\n"
            "# Naming: Q<root>[<Target><I|N>]...   I = joined INNER (columns keep\n"
            "# their catalog nullability), N = joined LEFT (the `| None` variant).\n"
            "# Single-edge shapes are generated for every declared edge; longer\n"
            "# shapes exist ONLY if joins.toml declared them. An undeclared\n"
            "# combination has no method at all -- that is the type-safety line."
        )
    )
    projections_by_shape: dict[str, list[str]] = {}
    for p in schema.projections:
        args = ", ".join(
            f"{_ns_ref(schema, p.shape_class, f.table)}.{_ident(f.column)}"
            for f in p.fields
        )
        projections_by_shape.setdefault(p.shape_class, []).append(
            f"    def {p.method}(self) -> Projection[{p.row_class}]:\n"
            f'        """Declared projection for this shape only."""\n'
            f"        return Projection(\n"
            f"            self.plan(),\n"
            f"            ({args},),\n"
            f"            {p.row_class},\n"
            f"        )"
        )

    for sh in schema.shapes:
        nulls = sh.nullability()
        out.append("@final")
        out.append(f"class {sh.class_name}(_QueryBase):")
        desc = " ".join(
            [f"FROM {sh.root}"]
            + [
                f"{'LEFT ' if s.kind == 'left' else ''}JOIN {s.target}"
                for s in sh.steps
            ]
        )
        out.append(f'    """{desc}."""')
        out.append("")
        out.append("    __slots__ = ()")
        for tname in [sh.root, *[s.target for s in sh.steps]]:
            t = schema.table(tname)
            if nulls[tname]:
                out.append(f"    {_ident(tname)}: {t.cols_n_class} = {t.const_n}")
            else:
                out.append(f"    {_ident(tname)}: {t.cols_class} = {t.const}")
        combos = _combinators(schema, sh)
        projs = projections_by_shape.get(sh.class_name, [])
        for block in combos + projs:
            out.append("")
            out.append(block)
        out.append("")
        out.append("")

    # ---- 6. entry points ---------------------------------------------------
    out.append(_rule("6. driving-table entry points"))
    root_shapes = {s.root: s for s in schema.shapes if not s.steps}
    for t in schema.tables:
        sh = root_shapes[t.name]
        out.append(f"def from_{t.name}() -> {sh.class_name}:")
        out.append(f'    return {sh.class_name}(_Plan("{t.name}"))')
        out.append("")
        out.append("")

    # ---- 7. typed writers --------------------------------------------------
    out.append(
        _rule(
            "7. typed writers.\n"
            "# INSERT checks COMPLETENESS (a NOT NULL column with no server default\n"
            "# is a required keyword) as well as types. UPDATE assignments are\n"
            "# TABLE-TAGGED: `update_orders(conn, USERS.email.set(...))` does not\n"
            "# type-check."
        )
    )
    for t in schema.tables:
        out.append(_insert_fn(t))
        out.append("")
        out.append("")
        out.append(
            f"def update_{t.name}(\n"
            f"    conn: Conn, *assigns: Assign[{t.tag}], where: Pred | None = None\n"
            f") -> int:\n"
            f'    """Typed UPDATE. Returns the affected row count."""\n'
            f'    return conn.update_rows("{t.name}", assigns, where)'
        )
        out.append("")
        out.append("")
        out.append(
            f"def delete_{t.name}(conn: Conn, *, where: Pred | None = None) -> int:\n"
            f'    """Typed DELETE. Returns the affected row count."""\n'
            f'    return conn.delete_rows("{t.name}", where)'
        )
        out.append("")
        out.append("")

    text = "\n".join(out)
    while "\n\n\n\n" in text:
        text = text.replace("\n\n\n\n", "\n\n\n")
    return text.rstrip("\n") + "\n"


def _ns_ref(schema: GSchema, shape_class: str, table: str) -> str:
    """How a projection method refers to a column namespace: `self.<alias>`."""
    del schema, shape_class
    return f"self.{_ident(table)}"


def _rule(title: str) -> str:
    bar = "# " + "-" * 74
    body = "\n".join(f"# {line}" if not line.startswith("#") else line
                     for line in title.split("\n"))
    return f"{bar}\n{body}\n{bar}\n"
